[[headers]]
  for = "/v1/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = GET, POST, PUT, DELETE
    Access-Control-Allow-Headers = Origin, X-Requested-With, Content-Type, Accept, Api-Key, Device-Key, Authorization
    X-Frame-Options = ALLOWALL